Ibw\JobeetBundle\Entity\UserInfo:
    type: entity
    table: user_info
    fields:
        userId:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: user_id
            generator:
                strategy: IDENTITY
        email:
            type: integer
            unsigned: false
            nullable: false
        name:
            type: string
            length: 50
            fixed: false
            nullable: false
        adree:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
