parameters:
#    admin_manage.example.class: Admin\ManageBundle\Example

services:
#    admin_manage.example:
#        class: %admin_manage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
